default_url_options:
  host: 'localhost:3000'
# この項目はメール本文にリンクを含む場合に必要。試しにlocalhost:300に変えてみたところメールのリンクでは
# localhost:300/~~~がURLになっていた。
# 調べてみたところ、メーラーはプロトコルが違うから、リクエストの情報を持っていないから明示的にURLを指定する必要があると
# 書かれていた。(HTTPとSMTPの違いって事かな？知識不足で詳しくわからなかった。)
redis:
  url: 'redis://localhost:6379'
